### ISSUE TITLE
Add testing to project

### ISSUE THREAD

**Issue by OverPoweredDev** [OverPoweredDev/Junior#1]
**Is your feature request related to a problem? Please describe.**
The project as it is right now has no testing. Commits are pushed directly to main and while not a problem usually, some tests would really be appreciated

**Describe the solution you'd like**
add flutter tests in src/lib/tests that run locally. Additional bonus if it's automated with Github Actions or TravisCI or something

**Describe alternatives you've considered**
Other automation CI tools are there but Actions would be best really

**Comment by Neha62-lit** [comment]
Hey @OverPoweredDev, I would like to work on this issue!

**Comment by OverPoweredDev** [comment]
Sure! Just note that if you add global keys and all to the main code, it might take a while to get merged

I'll still mark it with a `hacktoberfest-resolved` tag to make sure it gets counted, don't worry

**Comment by Neha62-lit** [comment]
Okay👍
