### ISSUE TITLE
Add new Tag for 'To Read' Novels

### ISSUE THREAD

**Issue by OverPoweredDev** [OverPoweredDev/Junior#14]
**Is your feature request related to a problem? Please describe.**
Noting down novels that you intend to read (sometime) is not possible with the current Release

**Describe the solution you'd like**
Add a 'To Read' tag similar to 'On Hiatus' that'll be set to `novelStatus`, along with an option to sort for it

**Comment by prabhav-pandya** [comment]
Omkar I'd like to work on this issue

**Comment by OverPoweredDev** [comment]
Sure no problem!
