### ISSUE TITLE
Look for a new Sorting interface

### ISSUE THREAD

**Issue by OverPoweredDev** [OverPoweredDev/Junior#19]
**Is your feature request related to a problem? Please describe.**
The current sorting interface is just a Dropdown with a whole buncha options. It's still alright at this point but it will begin to look very ugly later on

**Describe the solution you'd like**
A new Interface/Widget for the `sortOptions` class. One that ideally wouldn't look bad even with a buncha options

**Additional context**
I get that this is a bit vague but I really can't help it 😅. Just discuss your idea in the comments before implementing anything please

**Comment by prabhav-pandya** [comment]
@OverPoweredDev I would like to work on this

**Comment by OverPoweredDev** [comment]
Sure, go ahead
