### ISSUE TITLE
Add flutter-lints Dependency

### ISSUE THREAD

**Issue by Neha62-lit** [OverPoweredDev/Junior#9]
**Is your feature request related to a problem? Please describe.**
Yes, In issue no #1 there is need of flutter-lint dependency, because we need to test our app using GitHub Actions.
Github Actions help us to automate our software development workflows in the same place we store code and collaborate on pull requests and issues. The speed of Github Actions is good, and its pricing is better than that of Travis. 

**Describe the solution you'd like**
Linting is the process of analyzing a source code for any programming error, stylistic errors or any bug that can occur in the code. It is helpful, if you are working in a team, that way the whole team will follow some specific rules in the codebase. It's also helpful in identifying some common and uncommon mistakes that are made during coding like logical errors, unused variables etc.

**Additional context**
This is the package i propose to use here,
https://pub.dev/packages/flutter_lints

**Comment by Neha62-lit** [comment]
Hey @OverPoweredDev, Please assign this issue to me because for completing issue #1, I have to complete this issue first.

**Comment by OverPoweredDev** [comment]
Sure, no problem! I've been meaning to get CI/CD stuff up for a long time, I just get super distracted with new features 😅 

It'd be awesome if you could set linting and all up though, thanks! I'll put in the tags too so it counts

**Comment by OverPoweredDev** [comment]
I've merged the PR, good work on that! I'll close the issue once it's integrated with Github Actions

You can do it if you want, or leave it as is

**Comment by Neha62-lit** [comment]
Okay
